### ISSUE TITLE
[BUG] HA-MCP in-process server crashes with "cannot import name 'HeaderLineTooLong' from 'websockets.exceptions'" after updating Core to 2026.8.0

### ISSUE THREAD

**Issue by vishlamba** [homeassistant-ai/ha-mcp#2152]
**What happened?**
After updating Home Assistant Core from 2026.8.0b6 to 2026.8.0 (stable), 
the HA-MCP in-process server started crashing with an ImportError on startup.

**Error:**
HA-MCP in-process server failed to start: cannot import name 'HeaderLineTooLong' 
from 'websockets.exceptions' (/usr/local/lib/python3.14/site-packages/websockets/exceptions.py)

**Full traceback:**
File "/config/custom_components/ha_mcp_tools/embedded_server.py", line 1187, in _thread_main
    loop.run_until_complete(self._serve(access_token, stop_event))
File "/config/custom_components/ha_mcp_tools/embedded_server.py", line 1411, in _serve
    serve_task.result()
File "/usr/local/lib/python3.14/site-packages/uvicorn/server.py", line 81, in serve
    await self._serve(sockets)
File "/usr/local/lib/python3.14/site-packages/uvicorn/server.py", line 88, in _serve
    config.load()
File "/usr/local/lib/python3.14/site-packages/uvicorn/config.py", line 487, in load
    ws_protocol_class = import_from_string(WS_PROTOCOLS.get(self.ws, self.ws))
File "/usr/local/lib/python3.14/site-packages/uvicorn/importer.py", line 19, in import_from_string
    module = importlib.import_module(module_str)
File "/usr/local/lib/python3.14/site-packages/uvicorn/protocols/websockets/websockets_sansio_impl.py", line 21, in <module>
    from websockets.server import ServerProtocol
File "/usr/local/lib/python3.14/site-packages/websockets/server.py", line 13, in <module>
    from .exceptions import (
    ...<12 lines>...
    )
ImportError: cannot import name 'HeaderLineTooLong' from 'websockets.exceptions'

**Environment:**
- Home Assistant Core: 2026.8.0 (updated from 2026.8.0b6)
- Home Assistant OS: 18.2 (Home Assistant Green)
- Python: 3.14.6
- HA-MCP Custom Component: v8.1.0
- HA-MCP Server: 8.1.0

**Steps to reproduce:**
1. Have HA-MCP Custom Component running normally on Core 2026.8.0b6
2. Update Home Assistant Core to 2026.8.0 (stable)
3. HA-MCP in-process server fails to start with the ImportError above

**What I've tried:**
- Full restart of Home Assistant — did not resolve it
- Reloading the integration — did not resolve it

My guess is the Core 2026.8.0 update changed which version of the `websockets` 
package gets installed, and it's now incompatible with what HA-MCP's embedded 
uvicorn server expects.

**Comment by kingpanther13** [comment]
Duplicate of #2146 working on a fix right now
